name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 8点11分(北京时间 8点11分)
    - cron: 11 0 * * *
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: "${{ secrets.GLADOS_COOKIE }}"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master  
